### ISSUE TITLE
Submission Project

### ISSUE THREAD

**Issue by zhamri** [STIW3054-A182/Assignments#4]
# If completed, paste your PROJECT REPOSITORY link here.

**Comment by mwng97** [comment]
https://github.com/STIW3054-A182/Rojak-Repo

**Comment by shyyahcheang** [comment]
https://github.com/STIW3054-A182/HengOngHuat-Repo

**Comment by ChanJunLiang** [comment]
https://github.com/STIW3054-A182/BananaKing-Repo

**Comment by muhammadbimo1** [comment]
https://github.com/STIW3054-A182/-Prosciutto-Repo

**Comment by muhamaddarulhadi** [comment]
https://github.com/STIW3054-A182/Semput-Repo

**Comment by prevenkumar** [comment]
https://github.com/STIW3054-A182/CyberFox-Repo

**Comment by zhamri** [comment]
> https://github.com/STIW3054-A182/Rojak-Repo

[Rojak-Repo.txt](https://github.com/STIW3054-A182/Assignments/files/3219049/Rojak-Repo.txt)

**Comment by zhamri** [comment]
> https://github.com/STIW3054-A182/Rojak-Repo


[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building groupProject 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ groupProject ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/zhamricheani/Documents/STIW3054-A182-Projects/Rojak-Repo/Rojak-Repo-254301/groupProject/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ groupProject ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to /Users/zhamricheani/Documents/STIW3054-A182-Projects/Rojak-Repo/Rojak-Repo-254301/groupProject/target/classes
[INFO] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Rojak-Repo/Rojak-Repo-254301/groupProject/src/main/java/com/Stiw3054/groupProject/CountWiningPoint.java: /Users/zhamricheani/Documents/STIW3054-A182-Projects/Rojak-Repo/Rojak-Repo-254301/groupProject/src/main/java/com/Stiw3054/groupProject/CountWiningPoint.java uses unchecked or unsafe operations.
[INFO] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Rojak-Repo/Rojak-Repo-254301/groupProject/src/main/java/com/Stiw3054/groupProject/CountWiningPoint.java: Recompile with -Xlint:unchecked for details.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 53.002 s
[INFO] Finished at: 2019-05-25T10:11:58+08:00
[INFO] Final Memory: 13M/47M
[INFO] ------------------------------------------------------------------------

TotalClass:	13
TotalMean: 37.38461538461539
TotalMedian: 24.0
TotalStdDev: 40.92534721518131
TotalMin: 14.0
TotalMax: 165.0
TotalSum: 486.0

**Comment by zhamri** [comment]
> https://github.com/STIW3054-A182/HengOngHuat-Repo

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.groupProject.maven:GroupProject_A182:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 12, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building GroupProject_A182 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ GroupProject_A182 ---
[INFO] Deleting /Users/zhamricheani/Documents/STIW3054-A182-Projects/HengOngHuat-Repo/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ GroupProject_A182 ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ GroupProject_A182 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 20 source files to /Users/zhamricheani/Documents/STIW3054-A182-Projects/HengOngHuat-Repo/target/classes
[WARNING] /Users/zhamricheani/Documents/STIW3054-A182-Projects/HengOngHuat-Repo/src/main/java/com/groupProject/ValidTableLink.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/zhamricheani/Documents/STIW3054-A182-Projects/HengOngHuat-Repo/src/main/java/com/groupProject/ValidTableLink.java: Recompile with -Xlint:unchecked for details.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.942 s
[INFO] Finished at: 2019-05-25T10:22:15+08:00
[INFO] Final Memory: 13M/44M
[INFO] ------------------------------------------------------------------------

TotalClass:	20
TotalMean: 43.3
TotalMedian: 36.0
TotalStdDev: 29.447972224007348
TotalMin: 14.0
TotalMax: 121.0
TotalSum: 866.0

**Comment by zhamri** [comment]
> https://github.com/STIW3054-A182/BananaKing-Repo

[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building rtproject 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.2:resources (default-resources) @ rtproject ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/zhamricheani/Documents/STIW3054-A182-Projects/BananaKing-Repo/rtproject/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ rtproject ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 33 source files to /Users/zhamricheani/Documents/STIW3054-A182-Projects/BananaKing-Repo/rtproject/target/classes
[INFO] /Users/zhamricheani/Documents/STIW3054-A182-Projects/BananaKing-Repo/rtproject/src/main/java/com/rtproject/Part6.java: /Users/zhamricheani/Documents/STIW3054-A182-Projects/BananaKing-Repo/rtproject/src/main/java/com/rtproject/Part6.java uses unchecked or unsafe operations.
[INFO] /Users/zhamricheani/Documents/STIW3054-A182-Projects/BananaKing-Repo/rtproject/src/main/java/com/rtproject/Part6.java: Recompile with -Xlint:unchecked for details.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.811 s
[INFO] Finished at: 2019-05-25T09:44:25+08:00
[INFO] Final Memory: 13M/47M
[INFO] ------------------------------------------------------------------------

TotalClass:	33
TotalMean: 52.42424242424243
TotalMedian: 49.0
TotalStdDev: 43.69617982037436
TotalMin: 16.0
TotalMax: 265.0
TotalSum: 1730.0

**Comment by zhamri** [comment]
> https://github.com/STIW3054-A182/-Prosciutto-Repo

[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building project01 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ project01 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ project01 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to /Users/zhamricheani/Documents/STIW3054-A182-Projects/Prosciutto-Repo/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23.383 s
[INFO] Finished at: 2019-05-25T10:00:14+08:00
[INFO] Final Memory: 9M/40M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project project01: Compilation failure: Compilation failure: 
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by zhamri** [comment]
> https://github.com/STIW3054-A182/Semput-Repo

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.Semput.RealtimeProject:Semput_Project:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 12, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Semput_Project 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Semput_Project ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ Semput_Project ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 13 source files to /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[3,17] package org.jsoup does not exist
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[4,23] package org.jsoup.nodes does not exist
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[5,23] package org.jsoup.nodes does not exist
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[6,24] package org.jsoup.select does not exist
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[31,13] cannot find symbol
  symbol:   class Document
  location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[31,28] cannot find symbol
  symbol:   variable Jsoup
  location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[32,13] cannot find symbol
  symbol:   class Elements
  location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[34,13] cannot find symbol
  symbol:   class Elements
  location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[36,18] cannot find symbol
  symbol:   class Element
  location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[38,17] cannot find symbol
  symbol:   class Elements
  location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[49,22] cannot find symbol
  symbol:   class Element
  location: class Table
[INFO] 11 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.102 s
[INFO] Finished at: 2019-05-25T10:33:31+08:00
[INFO] Final Memory: 12M/44M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Semput_Project: Compilation failure: Compilation failure: 
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[3,17] package org.jsoup does not exist
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[4,23] package org.jsoup.nodes does not exist
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[5,23] package org.jsoup.nodes does not exist
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[6,24] package org.jsoup.select does not exist
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[31,13] cannot find symbol
[ERROR]   symbol:   class Document
[ERROR]   location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[31,28] cannot find symbol
[ERROR]   symbol:   variable Jsoup
[ERROR]   location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[32,13] cannot find symbol
[ERROR]   symbol:   class Elements
[ERROR]   location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[34,13] cannot find symbol
[ERROR]   symbol:   class Elements
[ERROR]   location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[36,18] cannot find symbol
[ERROR]   symbol:   class Element
[ERROR]   location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[38,17] cannot find symbol
[ERROR]   symbol:   class Elements
[ERROR]   location: class Table
[ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[49,22] cannot find symbol
[ERROR]   symbol:   class Element
[ERROR]   location: class Table
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by zhamri** [comment]
> https://github.com/STIW3054-A182/CyberFox-Repo

[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building maven-cyberfox-255392 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ maven-cyberfox-255392 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/zhamricheani/Documents/STIW3054-A182-Projects/CyberFox-Repo/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ maven-cyberfox-255392 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to /Users/zhamricheani/Documents/STIW3054-A182-Projects/CyberFox-Repo/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.007 s
[INFO] Finished at: 2019-05-25T10:35:52+08:00
[INFO] Final Memory: 9M/37M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project maven-cyberfox-255392: Compilation failure: Compilation failure: 
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by raihanwidia** [comment]
> > https://github.com/STIW3054-A182/-Prosciutto-Repo
> 
> [INFO] Scanning for projects...
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building project01 0.0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ project01 ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 1 resource
> [INFO]
> [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ project01 ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 19 source files to /Users/zhamricheani/Documents/STIW3054-A182-Projects/Prosciutto-Repo/target/classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] Source option 5 is no longer supported. Use 7 or later.
> [ERROR] Target option 5 is no longer supported. Use 7 or later.
> [INFO] 2 errors
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 23.383 s
> [INFO] Finished at: 2019-05-25T10:00:14+08:00
> [INFO] Final Memory: 9M/40M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project project01: Compilation failure: Compilation failure:
> [ERROR] Source option 5 is no longer supported. Use 7 or later.
> [ERROR] Target option 5 is no longer supported. Use 7 or later.
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Repo fixed

**Comment by prevenkumar** [comment]
https://github.com/STIW3054-A182/CyberFox-Repo

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building maven-cyberfox-255392 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ maven-cyberfox-255392 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/zhamricheani/Documents/STIW3054-A182-Projects/CyberFox-Repo/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ maven-cyberfox-255392 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to /Users/zhamricheani/Documents/STIW3054-A182-Projects/CyberFox-Repo/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.007 s
[INFO] Finished at: 2019-05-25T10:35:52+08:00
[INFO] Final Memory: 9M/37M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project maven-cyberfox-255392: Compilation failure: Compilation failure:
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Error fixed

**Comment by prevenkumar** [comment]
> > https://github.com/STIW3054-A182/CyberFox-Repo
> 
> [INFO] Scanning for projects...
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building maven-cyberfox-255392 0.0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ maven-cyberfox-255392 ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory /Users/zhamricheani/Documents/STIW3054-A182-Projects/CyberFox-Repo/src/main/resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ maven-cyberfox-255392 ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 12 source files to /Users/zhamricheani/Documents/STIW3054-A182-Projects/CyberFox-Repo/target/classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] Source option 5 is no longer supported. Use 7 or later.
> [ERROR] Target option 5 is no longer supported. Use 7 or later.
> [INFO] 2 errors
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 6.007 s
> [INFO] Finished at: 2019-05-25T10:35:52+08:00
> [INFO] Final Memory: 9M/37M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project maven-cyberfox-255392: Compilation failure: Compilation failure:
> [ERROR] Source option 5 is no longer supported. Use 7 or later.
> [ERROR] Target option 5 is no longer supported. Use 7 or later.
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Error Fixed

**Comment by muhamaddarulhadi** [comment]
> > https://github.com/STIW3054-A182/Semput-Repo
> 
> [INFO] Scanning for projects...
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for com.Semput.RealtimeProject:Semput_Project:jar:1.0-SNAPSHOT
> [WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 12, column 21
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building Semput_Project 1.0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Semput_Project ---
> [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
> [INFO] Copying 1 resource
> [INFO]
> [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ Semput_Project ---
> [INFO] Changes detected - recompiling the module!
> [WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
> [INFO] Compiling 13 source files to /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/target/classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[3,17] package org.jsoup does not exist
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[4,23] package org.jsoup.nodes does not exist
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[5,23] package org.jsoup.nodes does not exist
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[6,24] package org.jsoup.select does not exist
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[31,13] cannot find symbol
> symbol: class Document
> location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[31,28] cannot find symbol
> symbol: variable Jsoup
> location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[32,13] cannot find symbol
> symbol: class Elements
> location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[34,13] cannot find symbol
> symbol: class Elements
> location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[36,18] cannot find symbol
> symbol: class Element
> location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[38,17] cannot find symbol
> symbol: class Elements
> location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[49,22] cannot find symbol
> symbol: class Element
> location: class Table
> [INFO] 11 errors
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 14.102 s
> [INFO] Finished at: 2019-05-25T10:33:31+08:00
> [INFO] Final Memory: 12M/44M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Semput_Project: Compilation failure: Compilation failure:
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[3,17] package org.jsoup does not exist
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[4,23] package org.jsoup.nodes does not exist
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[5,23] package org.jsoup.nodes does not exist
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[6,24] package org.jsoup.select does not exist
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[31,13] cannot find symbol
> [ERROR] symbol: class Document
> [ERROR] location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[31,28] cannot find symbol
> [ERROR] symbol: variable Jsoup
> [ERROR] location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[32,13] cannot find symbol
> [ERROR] symbol: class Elements
> [ERROR] location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[34,13] cannot find symbol
> [ERROR] symbol: class Elements
> [ERROR] location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[36,18] cannot find symbol
> [ERROR] symbol: class Element
> [ERROR] location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[38,17] cannot find symbol
> [ERROR] symbol: class Elements
> [ERROR] location: class Table
> [ERROR] /Users/zhamricheani/Documents/STIW3054-A182-Projects/Semput-Repo/src/main/java/Table.java:[49,22] cannot find symbol
> [ERROR] symbol: class Element
> [ERROR] location: class Table
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

ERROR FIXED
